"""
Tests for auto-generated fluent API methods.

This test file verifies that all fluent API methods generated by generate_py.cpp
work correctly. Fluent methods allow calling methods on expressions directly
instead of going through the model.
"""

import optalcp as cp


def test_interval_var_fluent_expressions():
    """Test fluent expression methods on IntervalVar."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")

    # Test basic expression methods
    start = x.start()
    assert type(start).__name__ == 'IntExpr', "start() should return IntExpr"

    end = x.end()
    assert type(end).__name__ == 'IntExpr', "end() should return IntExpr"

    length = x.length()
    assert type(length).__name__ == 'IntExpr', "length() should return IntExpr"

    presence = x.presence()
    assert type(presence).__name__ == 'BoolExpr', "presence() should return BoolExpr"

    # Test that expressions can be used in constraints
    model.constraint(start >= 0)
    model.constraint(end <= 100)

    print("✓ test_interval_var_fluent_expressions passed")


def test_interval_var_precedence_constraints():
    """Test all precedence constraint fluent methods on IntervalVar."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=10, name="y")

    # Test end_before_start (already tested elsewhere but included for completeness)
    c1 = x.end_before_start(y)
    assert type(c1).__name__ == 'Constraint', "end_before_start should return Constraint"

    # Test with delay parameter
    c2 = x.end_before_start(y, delay=5)
    assert type(c2).__name__ == 'Constraint', "end_before_start with delay should return Constraint"

    # Test end_at_start
    c3 = x.end_at_start(y)
    assert type(c3).__name__ == 'Constraint', "end_at_start should return Constraint"

    # Test end_before_end
    c4 = x.end_before_end(y)
    assert type(c4).__name__ == 'Constraint', "end_before_end should return Constraint"

    # Test start_before_end
    c5 = x.start_before_end(y)
    assert type(c5).__name__ == 'Constraint', "start_before_end should return Constraint"

    # Test start_before_start
    c6 = x.start_before_start(y)
    assert type(c6).__name__ == 'Constraint', "start_before_start should return Constraint"

    # Test start_at_start
    c7 = x.start_at_start(y)
    assert type(c7).__name__ == 'Constraint', "start_at_start should return Constraint"

    # Test start_at_end
    c8 = x.start_at_end(y)
    assert type(c8).__name__ == 'Constraint', "start_at_end should return Constraint"

    # Test end_at_end
    c9 = x.end_at_end(y)
    assert type(c9).__name__ == 'Constraint', "end_at_end should return Constraint"

    print("✓ test_interval_var_precedence_constraints passed")


def test_intexpr_fluent_methods():
    """Test fluent methods on IntExpr."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    start = x.start()

    # Test abs()
    abs_expr = start.abs()
    assert type(abs_expr).__name__ == 'IntExpr', "abs() should return IntExpr"

    # Can use in constraint
    model.constraint(abs_expr >= 0)

    print("✓ test_intexpr_fluent_methods passed")


def test_sequence_var_fluent_methods():
    """Test fluent methods on SequenceVar."""
    model = cp.Model()

    # Create intervals for sequence
    tasks = [model.interval_var(length=10, name=f"task{i}") for i in range(3)]

    # Create sequence variable
    seq = model.sequence_var(tasks)

    # Test no_overlap fluent method
    seq.no_overlap()

    # Test no_overlap with transitions
    transitions = [
        [0, 5, 10],
        [5, 0, 5],
        [10, 5, 0]
    ]
    seq.no_overlap(transitions)

    print("✓ test_sequence_var_fluent_methods passed")


def test_fluent_api_with_solver():
    """Test that fluent API works end-to-end with solver."""
    model = cp.Model()

    # Create tasks using fluent API
    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=10, name="y")
    z = model.interval_var(length=10, name="z")

    # Use fluent methods for precedence
    x.end_before_start(y)
    y.end_before_start(z)

    # Use fluent expression methods
    model.constraint(x.start() >= 0)
    model.constraint(z.end() <= 100)

    # Minimize using fluent API
    model.minimize(z.end())

    # Solve
    result = cp.solve(model)

    assert result.nb_solutions > 0, "Should find solution using fluent API"
    assert result.objective_value == 30, f"Expected objective 30 (0+10+10+10), got {result.objective_value}"

    print(f"✓ test_fluent_api_with_solver passed: objective={result.objective_value}")


def test_fluent_vs_non_fluent_equivalence():
    """Test that fluent API produces same results as non-fluent API."""
    # Model 1: Using fluent API
    model1 = cp.Model()
    x1 = model1.interval_var(length=10, name="x")
    y1 = model1.interval_var(length=10, name="y")
    x1.end_before_start(y1)
    model1.constraint(x1.start() >= 0)
    model1.minimize(y1.end())

    # Model 2: Using non-fluent API (via model methods)
    model2 = cp.Model()
    x2 = model2.interval_var(length=10, name="x")
    y2 = model2.interval_var(length=10, name="y")
    model2.end_before_start(x2, y2)
    model2.constraint(model2.start_of(x2) >= 0)
    model2.minimize(model2.end_of(y2))

    # Both should produce same results
    result1 = cp.solve(model1)
    result2 = cp.solve(model2)

    assert result1.nb_solutions == result2.nb_solutions, "Should find same number of solutions"
    assert result1.objective_value == result2.objective_value, "Should have same objective value"

    print(f"✓ test_fluent_vs_non_fluent_equivalence passed: both got objective={result1.objective_value}")


def test_optional_parameters_in_fluent_methods():
    """Test that optional parameters work correctly in fluent methods."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=10, name="y")

    # Test with default delay (0)
    x.end_before_start(y)

    # Test with explicit delay
    x.end_before_start(y, delay=10)

    # Test with delay as expression
    delay_expr = model.int_var(min=0, max=100, name="delay")
    x.end_before_start(y, delay=delay_expr)

    print("✓ test_optional_parameters_in_fluent_methods passed")


def test_fluent_method_chaining_possibility():
    """Test that fluent methods return values that can be chained."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")

    # While we can't chain setter methods (they return None),
    # we can chain expression methods
    start = x.start()
    abs_start = start.abs()

    # This should work in a single line
    model.constraint(x.start().abs() >= 0)

    print("✓ test_fluent_method_chaining_possibility passed")

def test_start_or_with_solver():
    """Test start_or fluent method with solver."""
    model = cp.Model()

    # Create optional interval
    x = model.interval_var(length=10, optional=True, name="x")

    # If x is absent, use value 99, otherwise use actual start
    start_val = x.start_or(absentValue=99)

    # Make x absent
    x.make_absent()

    # The expression should evaluate to 99
    model.minimize(start_val)

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0, "Should find solution"
    assert result.objective_value == 99, f"start_or should return absentValue (99), got {result.objective_value}"

    print("✓ test_start_or_with_solver passed")


def test_end_or_with_solver():
    """Test end_or fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=10, optional=True, name="x")
    end_val = x.end_or(absentValue=88)

    x.make_absent()
    model.minimize(end_val)

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0
    assert result.objective_value == 88, f"end_or should return absentValue (88), got {result.objective_value}"

    print("✓ test_end_or_with_solver passed")


def test_length_or_with_solver():
    """Test length_or fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=(5, 15), optional=True, name="x")
    length_val = x.length_or(absentValue=77)

    x.make_absent()
    model.minimize(length_val)

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0
    assert result.objective_value == 77, f"length_or should return absentValue (77), got {result.objective_value}"

    print("✓ test_length_or_with_solver passed")


def test_end_at_end_with_solver():
    """Test end_at_end fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=10, name="y")

    # Both should end at the same time
    x.end_at_end(y)

    # Constrain x to start at 0
    model.constraint(x.start() == 0)

    # Should have x=[0,10], y=[?,10] where end(x)=end(y)=10
    model.minimize(y.start())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # x ends at 10, y must also end at 10, so y starts at 0
    assert result.objective_value == 0, f"Expected y.start=0, got {result.objective_value}"

    print("✓ test_end_at_end_with_solver passed")


def test_start_at_end_with_solver():
    """Test start_at_end fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=5, name="y")

    # y should start when x ends (so use y.start_at_end(x))
    y.start_at_end(x)

    model.constraint(x.start() == 0)
    model.minimize(y.end())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # x=[0,10], so y starts at 10, ends at 15
    assert result.objective_value == 15, f"Expected y.end=15, got {result.objective_value}"

    print("✓ test_start_at_end_with_solver passed")


def test_start_at_start_with_solver():
    """Test start_at_start fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=20, name="y")

    # Both should start at the same time
    x.start_at_start(y)

    model.constraint(x.start() == 5)
    model.minimize(y.end())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # x starts at 5, y also starts at 5, so y ends at 25
    assert result.objective_value == 25, f"Expected y.end=25, got {result.objective_value}"

    print("✓ test_start_at_start_with_solver passed")


def test_start_before_end_with_solver():
    """Test start_before_end fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=5, name="y")

    # x must start before y ends
    x.start_before_end(y)

    model.constraint(x.start() >= 0)
    model.constraint(y.start() >= 0)

    # Minimize x.start + y.start
    model.minimize(x.start() + y.start())

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0
    # Both should start at 0 since constraint allows it
    assert result.objective_value == 0, f"Expected 0, got {result.objective_value}"

    print("✓ test_start_before_end_with_solver passed")


def test_start_before_start_with_solver():
    """Test start_before_start fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")
    y = model.interval_var(length=10, name="y")

    # x must start before y starts
    x.start_before_start(y)

    model.constraint(x.start() >= 0)
    model.minimize(x.start() + y.start())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # x starts at 0, y can also start at 0 (before means <=)
    assert result.objective_value == 0, f"Expected 0, got {result.objective_value}"

    print("✓ test_start_before_start_with_solver passed")


def test_end_before_end_with_solver():
    """Test end_before_end fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=5, name="x")
    y = model.interval_var(length=10, name="y")

    # x must end before y ends
    x.end_before_end(y)

    model.constraint(x.start() >= 0)
    model.constraint(y.start() >= 0)

    # Minimize the sum of end times
    model.minimize(x.end() + y.end())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # x=[0,5], y can be [0,10] or [5,15], etc. Optimal: both start at 0
    assert result.objective_value == 15, f"Expected 15, got {result.objective_value}"

    print("✓ test_end_before_end_with_solver passed")


def test_alternative_with_solver():
    """Test alternative fluent method with solver."""
    model = cp.Model()

    # Main task X
    X = model.interval_var(length=10, name="X")

    # Alternative implementations
    XA = model.interval_var(optional=True, name="XA")
    XB = model.interval_var(optional=True, name="XB")

    # X is implemented by either XA or XB
    X.alternative([XA, XB])

    model.constraint(X.start() == 0)

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0, "Should find solution with alternative"

    print("✓ test_alternative_with_solver passed")


def test_span_with_solver():
    """Test span fluent method with solver."""
    model = cp.Model()

    # Parent task spans children
    parent = model.interval_var(name="parent")
    child1 = model.interval_var(length=5, name="child1")
    child2 = model.interval_var(length=5, name="child2")

    # Parent spans both children
    parent.span([child1, child2])

    # Children are sequential
    child1.end_before_start(child2)

    model.constraint(child1.start() == 0)
    model.minimize(parent.end())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # child1=[0,5], child2=[5,10], parent=[0,10]
    assert result.objective_value == 10, f"Expected parent.end=10, got {result.objective_value}"

    print("✓ test_span_with_solver passed")


def test_pulse_with_solver():
    """Test pulse fluent method with solver."""
    model = cp.Model()

    task = model.interval_var(length=10, name="task")

    # Pulse adds height during task execution
    cumul = task.pulse(height=3)

    # Capacity constraint
    cumul <= 5

    model.constraint(task.start() >= 0)
    model.minimize(task.start())

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0, "Should find solution with pulse"
    assert result.objective_value == 0, f"Expected 0, got {result.objective_value}"

    print("✓ test_pulse_with_solver passed")


def test_step_at_start_with_solver():
    """Test step_at_start fluent method with solver."""
    model = cp.Model()

    task = model.interval_var(length=10, name="task")

    # Step increases at task start
    cumul = task.step_at_start(height=2)

    # Must be non-negative
    cumul >= 0

    model.constraint(task.start() >= 0)
    model.minimize(task.start())

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0, "Should find solution with step_at_start"

    print("✓ test_step_at_start_with_solver passed")


def test_step_at_end_with_solver():
    """Test step_at_end fluent method with solver."""
    model = cp.Model()

    task = model.interval_var(length=10, name="task")

    # Step increases at task end
    cumul = task.step_at_end(height=-1)

    # Create another step to balance
    task2 = model.interval_var(length=5, name="task2")
    cumul2 = model.cumul_sum([task2.step_at_start(1), cumul])

    cumul2 >= 0

    model.constraint(task.start() == 0)
    model.minimize(task2.start())

    params = cp.Parameters(solutionLimit=1)
    result = cp.solve(model, params=params)

    assert result.nb_solutions > 0, "Should find solution with step_at_end"

    print("✓ test_step_at_end_with_solver passed")


def test_forbid_start_with_solver():
    """Test forbid_start fluent method with solver."""
    model = cp.Model()

    task = model.interval_var(length=5, name="task")

    # Create calendar: 1=allowed, 0=forbidden
    # Forbid starts during [5, 10)
    calendar = model.step_function([
        (0, 1),   # Initial value: allowed (1)
        (5, 0),   # At point 5: switch to forbidden (0)
        (10, 1)   # At point 10: switch back to allowed (1)
    ])

    # Task cannot start when calendar is 0
    task.forbid_start(calendar)

    # Try to minimize start
    model.minimize(task.start())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # Should start at 0 (allowed) or 10 (allowed), optimal is 0
    assert result.objective_value == 0, f"Expected start=0, got {result.objective_value}"

    print("✓ test_forbid_start_with_solver passed")


def test_forbid_end_with_solver():
    """Test forbid_end fluent method with solver."""
    model = cp.Model()

    task = model.interval_var(length=5, name="task")

    # Forbid ends during [5, 10)
    calendar = model.step_function([
        (0, 1),   # Initial value: allowed (1)
        (5, 0),   # At point 5: switch to forbidden (0)
        (10, 1)   # At point 10: switch back to allowed (1)
    ])

    task.forbid_end(calendar)

    model.constraint(task.start() >= 0)
    model.minimize(task.end())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # Task ends at 5 (forbidden) or later. Must end at 10 or after.
    # If start=0, end=5 (forbidden). So start must allow end >= 10.
    # Optimal: end at exactly 5 would be forbidden, so check it's not 5-9
    assert result.objective_value < 5 or result.objective_value >= 10, \
        f"End should not be in forbidden range [5,10), got {result.objective_value}"

    print("✓ test_forbid_end_with_solver passed")


def test_forbid_extent_with_solver():
    """Test forbid_extent fluent method with solver."""
    model = cp.Model()

    task = model.interval_var(length=5, name="task")

    # Forbid extents during [5, 10)
    calendar = model.step_function([
        (0, 1),   # Initial value: allowed (1)
        (5, 0),   # At point 5: switch to forbidden (0)
        (10, 1)   # At point 10: switch back to allowed (1)
    ])

    task.forbid_extent(calendar)

    model.minimize(task.start())

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # Task [start, end) cannot overlap with [5, 10) where calendar is 0
    # If start=0, end=5, that's ok (doesn't overlap forbidden)
    # If start=5, that overlaps forbidden, so not allowed
    assert result.objective_value == 0 or result.objective_value >= 10, \
        f"Task extent should not overlap [5,10), start={result.objective_value}"

    print("✓ test_forbid_extent_with_solver passed")


def test_position_with_solver():
    """Test position fluent method with solver."""
    model = cp.Model()

    tasks = [model.interval_var(length=5, name=f"task{i}") for i in range(3)]

    # Create sequence
    seq = model.sequence_var(tasks)
    seq.no_overlap()

    # Get position of first task in sequence
    pos = tasks[0].position(seq)

    # Minimize position of first task
    model.minimize(pos)

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # Position 0 is the first in sequence
    assert result.objective_value == 0, f"Expected position=0, got {result.objective_value}"

    print("✓ test_position_with_solver passed")


def test_intexpr_abs_with_solver():
    """Test IntExpr.abs() fluent method with solver."""
    model = cp.Model()

    x = model.interval_var(length=10, name="x")

    # Create expression for start - 5
    diff = x.start() - 5

    # Get absolute value
    abs_diff = diff.abs()

    # Minimize absolute difference from 5
    model.minimize(abs_diff)

    result = cp.solve(model)

    assert result.nb_solutions > 0
    # Should start at 5 to minimize |start - 5|
    assert result.objective_value == 0, f"Expected |5-5|=0, got {result.objective_value}"

    print("✓ test_intexpr_abs_with_solver passed")


if __name__ == "__main__":
    print("Running fluent API tests...")
    print()

    # Basic functionality tests
    test_interval_var_fluent_expressions()
    test_interval_var_precedence_constraints()
    test_intexpr_fluent_methods()
    test_sequence_var_fluent_methods()
    test_fluent_api_with_solver()
    test_fluent_vs_non_fluent_equivalence()
    test_optional_parameters_in_fluent_methods()
    test_fluent_method_chaining_possibility()

    # Comprehensive solver tests for each fluent method
    print()
    print("Running comprehensive solver tests for each fluent method...")
    print()
    test_start_or_with_solver()
    test_end_or_with_solver()
    test_length_or_with_solver()
    test_end_at_end_with_solver()
    test_start_at_end_with_solver()
    test_start_at_start_with_solver()
    test_start_before_end_with_solver()
    test_start_before_start_with_solver()
    test_end_before_end_with_solver()
    test_alternative_with_solver()
    test_span_with_solver()
    test_pulse_with_solver()
    test_step_at_start_with_solver()
    test_step_at_end_with_solver()
    test_forbid_start_with_solver()
    test_forbid_end_with_solver()
    test_forbid_extent_with_solver()
    # TODO: test_position_with_solver() causes solver crash - needs investigation
    test_position_with_solver()
    test_intexpr_abs_with_solver()

    print()
    print("All fluent API tests passed! ✓")
